# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ssc_widget.ui'
#
# Created: Thu Sep  4 11:31:35 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(885, 476)
        TabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.multipartyTab = QtGui.QWidget()
        self.multipartyTab.setObjectName(_fromUtf8("multipartyTab"))
        self.groupBox = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 221, 211))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.sliderMaliciousness = QtGui.QSlider(self.groupBox)
        self.sliderMaliciousness.setGeometry(QtCore.QRect(90, 30, 21, 160))
        self.sliderMaliciousness.setMinimum(1)
        self.sliderMaliciousness.setMaximum(5)
        self.sliderMaliciousness.setPageStep(4)
        self.sliderMaliciousness.setProperty("value", 1)
        self.sliderMaliciousness.setOrientation(QtCore.Qt.Vertical)
        self.sliderMaliciousness.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderMaliciousness.setTickInterval(1)
        self.sliderMaliciousness.setObjectName(_fromUtf8("sliderMaliciousness"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(120, 30, 61, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(120, 100, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 61, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sliderAdaptiveness = QtGui.QSlider(self.groupBox)
        self.sliderAdaptiveness.setGeometry(QtCore.QRect(190, 30, 21, 160))
        self.sliderAdaptiveness.setMinimum(1)
        self.sliderAdaptiveness.setMaximum(5)
        self.sliderAdaptiveness.setSingleStep(2)
        self.sliderAdaptiveness.setPageStep(2)
        self.sliderAdaptiveness.setOrientation(QtCore.Qt.Vertical)
        self.sliderAdaptiveness.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderAdaptiveness.setTickInterval(2)
        self.sliderAdaptiveness.setObjectName(_fromUtf8("sliderAdaptiveness"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(120, 170, 52, 15))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 230, 331, 211))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.cbMixedAdversary = QtGui.QCheckBox(self.groupBox_2)
        self.cbMixedAdversary.setGeometry(QtCore.QRect(250, 80, 121, 31))
        self.cbMixedAdversary.setObjectName(_fromUtf8("cbMixedAdversary"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sliderFairness = QtGui.QSlider(self.groupBox_2)
        self.sliderFairness.setGeometry(QtCore.QRect(220, 30, 21, 160))
        self.sliderFairness.setMinimum(1)
        self.sliderFairness.setMaximum(5)
        self.sliderFairness.setPageStep(2)
        self.sliderFairness.setProperty("value", 1)
        self.sliderFairness.setOrientation(QtCore.Qt.Vertical)
        self.sliderFairness.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderFairness.setTickInterval(1)
        self.sliderFairness.setObjectName(_fromUtf8("sliderFairness"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 101, 41))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(140, 130, 81, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(140, 30, 81, 31))
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cbComposable = QtGui.QCheckBox(self.groupBox_2)
        self.cbComposable.setGeometry(QtCore.QRect(250, 50, 91, 21))
        self.cbComposable.setAutoFillBackground(False)
        self.cbComposable.setObjectName(_fromUtf8("cbComposable"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(140, 60, 71, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.sliderSecType = QtGui.QSlider(self.groupBox_2)
        self.sliderSecType.setGeometry(QtCore.QRect(110, 30, 21, 160))
        self.sliderSecType.setMinimum(1)
        self.sliderSecType.setMaximum(5)
        self.sliderSecType.setPageStep(2)
        self.sliderSecType.setProperty("value", 1)
        self.sliderSecType.setSliderPosition(1)
        self.sliderSecType.setOrientation(QtCore.Qt.Vertical)
        self.sliderSecType.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderSecType.setTickInterval(1)
        self.sliderSecType.setObjectName(_fromUtf8("sliderSecType"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(140, 90, 81, 31))
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(140, 170, 81, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.groupBox_3 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 230, 91, 211))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.sliderCorruptedParties = QtGui.QSlider(self.groupBox_3)
        self.sliderCorruptedParties.setGeometry(QtCore.QRect(60, 30, 21, 160))
        self.sliderCorruptedParties.setMinimum(1)
        self.sliderCorruptedParties.setMaximum(5)
        self.sliderCorruptedParties.setPageStep(3)
        self.sliderCorruptedParties.setProperty("value", 1)
        self.sliderCorruptedParties.setOrientation(QtCore.Qt.Vertical)
        self.sliderCorruptedParties.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderCorruptedParties.setTickInterval(1)
        self.sliderCorruptedParties.setObjectName(_fromUtf8("sliderCorruptedParties"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 135, 51, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 51, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_4 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 201, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.cbSynchronous = QtGui.QCheckBox(self.groupBox_4)
        self.cbSynchronous.setGeometry(QtCore.QRect(10, 110, 131, 21))
        self.cbSynchronous.setChecked(True)
        self.cbSynchronous.setObjectName(_fromUtf8("cbSynchronous"))
        self.cbTrustedSetup = QtGui.QCheckBox(self.groupBox_4)
        self.cbTrustedSetup.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.cbTrustedSetup.setChecked(True)
        self.cbTrustedSetup.setObjectName(_fromUtf8("cbTrustedSetup"))
        self.cbBroadcast = QtGui.QCheckBox(self.groupBox_4)
        self.cbBroadcast.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.cbBroadcast.setChecked(True)
        self.cbBroadcast.setObjectName(_fromUtf8("cbBroadcast"))
        self.cbPrivateChannels = QtGui.QCheckBox(self.groupBox_4)
        self.cbPrivateChannels.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.cbPrivateChannels.setChecked(True)
        self.cbPrivateChannels.setObjectName(_fromUtf8("cbPrivateChannels"))
        self.lblProtocolsFound = QtGui.QLabel(self.multipartyTab)
        self.lblProtocolsFound.setGeometry(QtCore.QRect(420, 10, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lblProtocolsFound.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblProtocolsFound.setFont(font)
        self.lblProtocolsFound.setObjectName(_fromUtf8("lblProtocolsFound"))
        self.groupBox_6 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setGeometry(QtCore.QRect(120, 490, 331, 41))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.radioExact = QtGui.QRadioButton(self.groupBox_6)
        self.radioExact.setGeometry(QtCore.QRect(60, 20, 89, 19))
        self.radioExact.setObjectName(_fromUtf8("radioExact"))
        self.radioAtLeast = QtGui.QRadioButton(self.groupBox_6)
        self.radioAtLeast.setGeometry(QtCore.QRect(180, 20, 89, 19))
        self.radioAtLeast.setChecked(True)
        self.radioAtLeast.setObjectName(_fromUtf8("radioAtLeast"))
        self.listView = QtGui.QListView(self.multipartyTab)
        self.listView.setGeometry(QtCore.QRect(410, 40, 361, 121))
        self.listView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.groupBox_7 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_7.setGeometry(QtCore.QRect(680, 230, 191, 211))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.sliderOnlineComm = QtGui.QSlider(self.groupBox_7)
        self.sliderOnlineComm.setGeometry(QtCore.QRect(80, 30, 23, 160))
        self.sliderOnlineComm.setMinimum(1)
        self.sliderOnlineComm.setMaximum(5)
        self.sliderOnlineComm.setPageStep(4)
        self.sliderOnlineComm.setOrientation(QtCore.Qt.Vertical)
        self.sliderOnlineComm.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderOnlineComm.setTickInterval(1)
        self.sliderOnlineComm.setObjectName(_fromUtf8("sliderOnlineComm"))
        self.label_25 = QtGui.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 61, 41))
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(10, 130, 61, 31))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(20, 190, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.cbConstantRounds = QtGui.QCheckBox(self.groupBox_7)
        self.cbConstantRounds.setGeometry(QtCore.QRect(110, 50, 101, 31))
        self.cbConstantRounds.setObjectName(_fromUtf8("cbConstantRounds"))
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setGeometry(QtCore.QRect(10, 160, 61, 31))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.btnSetSliders = QtGui.QPushButton(self.multipartyTab)
        self.btnSetSliders.setGeometry(QtCore.QRect(410, 170, 151, 25))
        self.btnSetSliders.setObjectName(_fromUtf8("btnSetSliders"))
        self.groupBox_8 = QtGui.QGroupBox(self.multipartyTab)
        self.groupBox_8.setGeometry(QtCore.QRect(220, 0, 161, 211))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.sliderPreprocComm = QtGui.QSlider(self.groupBox_8)
        self.sliderPreprocComm.setGeometry(QtCore.QRect(80, 30, 23, 160))
        self.sliderPreprocComm.setMinimum(1)
        self.sliderPreprocComm.setMaximum(5)
        self.sliderPreprocComm.setPageStep(4)
        self.sliderPreprocComm.setProperty("value", 1)
        self.sliderPreprocComm.setOrientation(QtCore.Qt.Vertical)
        self.sliderPreprocComm.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sliderPreprocComm.setTickInterval(1)
        self.sliderPreprocComm.setObjectName(_fromUtf8("sliderPreprocComm"))
        self.label_31 = QtGui.QLabel(self.groupBox_8)
        self.label_31.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.groupBox_8)
        self.label_32.setGeometry(QtCore.QRect(10, 50, 61, 51))
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_8)
        self.label_33.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_35 = QtGui.QLabel(self.groupBox_8)
        self.label_35.setGeometry(QtCore.QRect(10, 190, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(10, 160, 61, 31))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_8)
        self.label_37.setGeometry(QtCore.QRect(10, 120, 61, 41))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.groupBoxImpl = QtGui.QGroupBox(self.multipartyTab)
        self.groupBoxImpl.setGeometry(QtCore.QRect(10, 160, 201, 51))
        self.groupBoxImpl.setTitle(_fromUtf8(""))
        self.groupBoxImpl.setObjectName(_fromUtf8("groupBoxImpl"))
        self.cbImplemented = QtGui.QCheckBox(self.groupBoxImpl)
        self.cbImplemented.setGeometry(QtCore.QRect(10, 9, 111, 31))
        self.cbImplemented.setObjectName(_fromUtf8("cbImplemented"))
        self.btnResetSliders = QtGui.QPushButton(self.multipartyTab)
        self.btnResetSliders.setGeometry(QtCore.QRect(580, 170, 111, 25))
        self.btnResetSliders.setObjectName(_fromUtf8("btnResetSliders"))
        TabWidget.addTab(self.multipartyTab, _fromUtf8(""))
        self.label_4.setBuddy(self.sliderMaliciousness)
        self.label_2.setBuddy(self.sliderMaliciousness)
        self.label_9.setBuddy(self.sliderAdaptiveness)
        self.label_3.setBuddy(self.sliderMaliciousness)
        self.label_8.setBuddy(self.sliderAdaptiveness)
        self.label_6.setBuddy(self.sliderMaliciousness)
        self.label_7.setBuddy(self.sliderAdaptiveness)

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "SSC Protocol Comparison Tool", None))
        self.groupBox.setTitle(_translate("TabWidget", "Adversary", None))
        self.label_4.setText(_translate("TabWidget", "Covert", None))
        self.label_2.setText(_translate("TabWidget", "Passive", None))
        self.label_9.setText(_translate("TabWidget", "Mobile", None))
        self.label_3.setText(_translate("TabWidget", "Malicious", None))
        self.label_8.setText(_translate("TabWidget", "Adaptive", None))
        self.label_6.setText(_translate("TabWidget", "Fail-stop", None))
        self.label_7.setText(_translate("TabWidget", "Static", None))
        self.groupBox_2.setTitle(_translate("TabWidget", "Security", None))
        self.cbMixedAdversary.setText(_translate("TabWidget", "Mixed \n"
"Adversary", None))
        self.label_11.setText(_translate("TabWidget", "Computational", None))
        self.label_10.setText(_translate("TabWidget", "Statistical Unconditional", None))
        self.label.setText(_translate("TabWidget", "Perfect Unconditional", None))
        self.label_12.setText(_translate("TabWidget", "No Fairness", None))
        self.label_14.setText(_translate("TabWidget", "Guaranteed Output", None))
        self.cbComposable.setText(_translate("TabWidget", "UC", None))
        self.label_13.setText(_translate("TabWidget", "Fair Abort", None))
        self.label_23.setText(_translate("TabWidget", "Weakened", None))
        self.label_24.setText(_translate("TabWidget", "Partial Fairness", None))
        self.label_20.setText(_translate("TabWidget", "No Agreement", None))
        self.groupBox_3.setTitle(_translate("TabWidget", "Corruptions", None))
        self.label_18.setText(_translate("TabWidget", "< n", None))
        self.label_16.setText(_translate("TabWidget", "< n/3", None))
        self.label_17.setText(_translate("TabWidget", "< n/2", None))
        self.label_15.setText(_translate("TabWidget", "< n/4", None))
        self.groupBox_4.setTitle(_translate("TabWidget", "Environment Features Available", None))
        self.cbSynchronous.setText(_translate("TabWidget", "Synchronous", None))
        self.cbTrustedSetup.setText(_translate("TabWidget", "Trusted Setup", None))
        self.cbBroadcast.setText(_translate("TabWidget", "Broadcast Channel", None))
        self.cbPrivateChannels.setText(_translate("TabWidget", "Private Channels", None))
        self.lblProtocolsFound.setText(_translate("TabWidget", "Protocols Found", None))
        self.groupBox_6.setTitle(_translate("TabWidget", "Slider Levels", None))
        self.radioExact.setText(_translate("TabWidget", "Exact", None))
        self.radioAtLeast.setText(_translate("TabWidget", "At Least", None))
        self.listView.setToolTip(_translate("TabWidget", "Double-click a result to see a popup abstract.", None))
        self.groupBox_7.setTitle(_translate("TabWidget", "Online Comm Efficiency", None))
        self.label_25.setText(_translate("TabWidget", "Linear", None))
        self.label_26.setText(_translate("TabWidget", "\"Near-linear\"", None))
        self.label_27.setText(_translate("TabWidget", "Quadratic", None))
        self.label_28.setText(_translate("TabWidget", "> Quad", None))
        self.label_29.setText(_translate("TabWidget", "Complexity per gate, in n", None))
        self.cbConstantRounds.setText(_translate("TabWidget", "Constant \n"
"Rounds", None))
        self.label_30.setText(_translate("TabWidget", ">= Cubic", None))
        self.btnSetSliders.setText(_translate("TabWidget", "Set sliders from protocol", None))
        self.groupBox_8.setTitle(_translate("TabWidget", "Preprocessing Comm.", None))
        self.label_31.setText(_translate("TabWidget", "None", None))
        self.label_32.setText(_translate("TabWidget", "Sublinear", None))
        self.label_33.setText(_translate("TabWidget", "Linear", None))
        self.label_35.setText(_translate("TabWidget", "Complexity per gate, in n", None))
        self.label_36.setText(_translate("TabWidget", "<html><head/><body><p>&gt;Quadratic</p></body></html>", None))
        self.label_37.setText(_translate("TabWidget", "Quadratic", None))
        self.cbImplemented.setText(_translate("TabWidget", "Implemented", None))
        self.btnResetSliders.setText(_translate("TabWidget", "Reset Sliders", None))
        TabWidget.setTabText(TabWidget.indexOf(self.multipartyTab), _translate("TabWidget", "Multiparty Universal Computation", None))

